version: "3.9"

services:
  air:
    image: cosmtrek/air:v1.49.0
    working_dir: /app
    ports:
      - 3000:3000
    depends_on:
      redis:
        condition: service_healthy
      db_migrate:
        condition: service_completed_successfully

    volumes:
      - .:/app

  app:
    build: .
    ports:
      - 3000:3000
    depends_on: 
      redis:
        condition: service_healthy
      db_migrate:
        condition: service_completed_successfully
  
  redis:
    container_name: redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass todo
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

  db_migrate:
    container_name: db_migrate
    image: migrate/migrate:4
    volumes: 
      - ./migrations:/migrations
    entrypoint: ["migrate", "-path", "/migrations", "-database", "postgresql://todo:todo@postgres_db:5432/todo?sslmode=disable", "up"]
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: postgres_db
    image: postgres:16.0
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  
    