development:
  dialect: postgres
  database: bookings
  user: bookings
  password: bookings
  host: 0.0.0.0
  port: 6000
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@0.0.0.0:6000/myapp_test"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@0.0.0.0:6000/myapp_production"}}